name: Deployment Build

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    environment: Building
    strategy:
      matrix:
        os: [macOS-latest, windows-2019, ubuntu-latest]
        include:
          - os: ubuntu-latest
            command: |
                sudo apt-get update && sudo apt install libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev libsoup2.4-dev
                cargo install cargo-bundle
                ./build_linux.sh
            binary: target/release/bundle/deb/twatvault_0.1.0_amd64.deb
          - os: macOS-latest
            command: |
                rustup target add aarch64-apple-darwin
                rustup target add x86_64-apple-darwin
                cargo install cargo-bundle
                ./build_mac.sh
            binary: target/twatvault.zip
          - os: windows-2019
            command: |
                .\build_windows.bat
            binary: target\release\twatvault.exe
    steps:
      - name: Production Build
        uses: actions/checkout@v2
      - run: |
          ${{ matrix.command }}
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ matrix.binary }}
